# This is a basic workflow to help you get started with Actions

name: Update status for Business Rates

# Controls when the workflow will run
on:
  schedule:
  #  - cron: '0 7 1 * *'
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
      - index.csv
      - status.csv

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install cpanm and multiple modules
        uses: perl-actions/install-with-cpanm@v1
        with:
          install: List::Util

      # Runs script
      - name: Update status
        working-directory: ./
        run: |
          perl status.pl
      - name: Commit changes to files
        working-directory: ./
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add status.csv
          git add status.html
          git add data/*
          git commit -m "Update status" || exit 0
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}